# Generated by Django 2.2 on 2019-07-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_ems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ems',
            old_name='emsnumber',
            new_name='ems_number',
        ),
    ]
